### ISSUE TITLE
Stateless JWT

### ISSUE THREAD

**Issue by deepcover96** [mohiva/play-silhouette-angular-seed#12]
From the documentation: "An authenticator that uses a header-based approach with the help of a JWT (JSON Web Token). It works by using a JWT to transport the authenticator data inside a user defined header. It can be stateless with the disadvantages that the JWT can’t be invalidated."

I would have thought that a JWT would still be valid after a server reset if the server secret hasn't changed.  I tried this on the play-silhouette-angular-seed and the token is invalid after you restart the server, forcing me to negotiate for a new one.

Is my understanding of JWT incorrect, or is there a way in Silhouette to make the JWT Authenticator behave in this way?

I am using PostgreSQL on the back-end.  Do I have to save the JWT Authenticator objects to the database to have the behavior that I need, like you would with the user data?  Would using the trait AuthenticatorDAO be what I need to implement this.  If so, is there a gist or example that can help with this particular case?

I need to save JWTs to a database anyway so that I can have a way to invalidate them, so this type of approach would still be welcomed.

Thank you for your time.

**Comment by akkie** [comment]
Mhhh, this is strange. I'm sure that the functionally is implemented as described. Do you have a log entry or an exception?

As you noted, a token must only be persisted if the possibility to invalidate it should be in place. For this case you must implement the `AuthenticatorDAO` and pass it to the authenticator service. I've no code snippet for this case, but this should be straight forward.

**Comment by deepcover96** [comment]
Thank you for the response.  There is no issue, it was all me not understanding how to use the Authenticator.  In the example, the JWT Authenticator is set to use the CacheAuthenticatorDAO, which now makes sense that restarting the server invalidates the previous tokens.  Once I changed the DAO to None in (/app/utils/di/SilhouetteModule.scala) provideAuthenticatorService, it worked in a stateless manner.

Thanks for your hard work, I'm learning a lot just by using your library.
