### ISSUE TITLE
Update to Play 2.4 and Silhouette 3.0

### ISSUE THREAD

**Issue by akkie** [mohiva/play-silhouette-angular-seed#14]
This template depends on play-yeoman which isn't updated to Play 2.4 at this time. There exists an open [pull request](https://github.com/tuplejump/play-yeoman/pull/65) to solve this issue.

**Comment by diwalak** [comment]
play-yeoman is now updated for play 2.4

It would be great to have an update to this project

**Comment by akkie** [comment]
If I find the time then at the end of the week. Otherwise at the end of the next week.

**Comment by djonmayer** [comment]
+1

**Comment by akkie** [comment]
Please see #15

**Comment by akkie** [comment]
Fixed. But note there is an [open issue](https://github.com/mohiva/play-silhouette-angular-seed/issues/18) which stops the Twitter support.
