### ISSUE TITLE
Csrf-Token

### ISSUE THREAD

**Issue by Fours** [mohiva/play-silhouette-angular-seed#29]
I'm curious why the csrf token is used by angular. Setting a csfr-token header value to "nocheck" would achieve the same amount of security against csfr attacks. So is the benefit of the token to simply future proof against possible vulnerabilities? Or is there another current vulnerability that it protects against?

**Comment by Fours** [comment]
Also have a similar question for why "application/json" is included in the csfr blacklist. Thanks.

**Comment by akkie** [comment]
It's an example which shows how the token can be implemented on the Play and the Angular side and I think it provides the most secure way now and in the future. 

> Also have a similar question for why "application/json" is included in the csfr blacklist. Thanks.

In this example forms are submitted via Json so it's needed to check for the CSFR token.

**Comment by Fours** [comment]
Thanks for the reply. I appreciate the framework and example app. The goal of my question was just to find out if there are some vulnerabilities that I'm unaware of, which are addressed by this implementation. CSFR attacks can't be made by posting application/json or by setting custom headers. But I understand it doesn't hurt to be "over" secure when it comes to web apps.

**Comment by akkie** [comment]
Nice to hear that you like the lib :+1: 

Yes, currently it isn't possible and I was first unsure if I should implement the token in the example. But then I've read [this](http://security.stackexchange.com/a/10231) on Security StackExchange.
