### ISSUE TITLE
Unable to login with Google 

### ISSUE THREAD

**Issue by fib3rwire** [mohiva/play-silhouette-angular-seed#30]
Hi,
i'm unable to login with Google social provider with Satellizer.

First request pass and I got oauth2 response. 
Satellizer is calling google auth endpoint twice and on my backend it ends up with exception on second request: 

<pre>
[debug] c.m.p.s.i.p.o.GoogleProvider - [Silhouette][google] Access token response: [{
  "error" : "invalid_grant",
  "error_description" : "Code was already redeemed."
}]
</pre>

<pre>
[error] s.b.i.c.SocialAuthController - Unexpected provider error
com.mohiva.play.silhouette.impl.exceptions.UnexpectedResponseException: [Silhouette][google] Cannot build OAuth2Info because of invalid response format: List((/access_token,List(ValidationError(List(error.path.missing),WrappedArray()))))
	at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:165) ~[play-silhouette_2.11-3.0.0.jar:3.0.0]
....
</pre>

I've everything set up correctly, at least I think so :)

Satellizer: 
```javascript
 $authProvider.google({
		clientId: '<my_client_id>',
	  	url: '<my_auth_endpoint>',
	    authorizationEndpoint: 'https://accounts.google.com/o/oauth2/auth',
		redirectUri: window.location.origin +  '<my_auth_endpoint>' || window.location.protocol + '//' + window.location.host + '<my_auth_endpoint>',
		requiredUrlParams: ['scope'],
	    optionalUrlParams: ['display'],
	    scope: ['profile', 'email'],
	    scopePrefix: 'openid',
	    scopeDelimiter: ' ',
	    display: 'popup',
	    type: '2.0',
	    popupOptions: { width: 452, height: 633 }
    });
```

silhouette.conf
<pre>
 google.accessTokenURL="https://accounts.google.com/o/oauth2/token"
  google.redirectURL="<my_auth_endpoint>"
  google.clientID="<my_client_id>'"
  google.clientSecret="<my_client_secret>'"
  google.scope="profile email"
</pre>

What could be the problem please?

**Comment by akkie** [comment]
I'm not sure. If you test the [example application](https://play-silhouette-angular-seed.herokuapp.com), then it works as expected. Do you use the bundled version of Satellizer? A newer version may not work as expected.

**Comment by fib3rwire** [comment]
@akkie Hi, I used same version now for a try out (0.10.1) - same result, no luck :(

**Comment by fib3rwire** [comment]
@akkie I tried Twitter (and it's working fine, I suppose because cacheAuthTokenForOauth1 is used.

Now I tried FB and same problem like with Google =>

<pre>
[debug] c.m.p.s.i.p.o.FacebookProvider - [Silhouette][facebook] Access token response: [{"error":{"message":"This authorization code has been used.","type":"OAuthException","code":100,"fbtrace_id":"CbqIj5bHjNg"}}]
</pre>

**Comment by akkie** [comment]
Hi,

Sorry for the late reply but I had last week off.

I cannot reproduce the issue. Please can you provide an example which show the issue? Have you tried the [example app](https://play-silhouette-angular-seed.herokuapp.com/#/signIn)? This works as expected and this is the same code as in this repository.

Cheers,
Christian

**Comment by fib3rwire** [comment]
Hi @akkie I'll look further into this issue as I'll have more time. 

P.S.: I built our IAM based on that example... :/

**Comment by akkie** [comment]
I the issue solved?

**Comment by akkie** [comment]
Please open the issue again if it's not solved.

**Comment by miguelbaldi** [comment]
I'm facing the same issue. The example app does not work with facebook and google, maybe other providers. Only works with Twitter.

**Comment by akkie** [comment]
@miguelbaldi Thanks, it has used the wrong credentials for Facebook and Google. Now it works as expected.
