### ISSUE TITLE
Websockets example

### ISSUE THREAD

**Issue by pbvie** [mohiva/play-silhouette-angular-seed#31]
Could you add an example of how to access a secured websocket?

Thanks,
Petra

**Comment by akkie** [comment]
Hi, 

There is an example in the documentation.

http://silhouette.mohiva.com/docs/endpoints#websockets

Best regards, 
Christian

**Comment by pbvie** [comment]
Thank you, but the example uses the CookieAuthenticator - I'd like to know how I can use secured websockets with JWTAuthenticator and tokens.

I tried the approach from the link above, but the X-Auth-Token header containing the token isn't added when opening a websocket connection.

**Comment by akkie** [comment]
Please see http://silhouette.mohiva.com/v3.0/discuss/55950f4935f567170094304c

I currently work on this issue. But the fix will only be available with version 4.0
