### ISSUE TITLE
Unable to start play-silhouette-angular-seed from Heroku

### ISSUE THREAD

**Issue by renexdev** [mohiva/play-silhouette-angular-seed#32]
Hi guys,
I'm trying to test the app in Heroku, after figuring out some settings with npm, that I solved running in the heroku-toolbelt:
heroku buildpacks:set https://github.com/ddollar/heroku-buildpack-multi.git
heroku config:set NPM_CONFIG_PRODUCTION=false

I got a successfully deployed app, but at the moment of starting  I got Application Error. After doing heroku logs I got the following: 
...
 Picked up JAVA_TOOL_OPTIONS: -Xmx350m -Xss512k -Dfile.encoding=UTF-8
2015-12-08T18:44:11.319118+00:00 app[web.1]: Oops, cannot start the server.
2015-12-08T18:44:11.327327+00:00 app[web.1]: 	at play.api.Configuration$.configError(Configuration.scala:178)
2015-12-08T18:44:11.327440+00:00 app[web.1]: 	at play.core.server.ProdServerStart$.readServerConfigSettings(ProdServerStart.scala:81)
2015-12-08T18:44:11.327389+00:00 app[web.1]: 	at play.api.Configuration$.load(Configuration.scala:103)
2015-12-08T18:44:11.327856+00:00 app[web.1]: Caused by: com.typesafe.config.ConfigException$Parse:  @ file:/app/target/universal/stage/conf/: 2: Key 'application.conf' may not be followed by token: 'application.prod.conf' (if you intended 'application.prod.conf' to be part of a key or string value, try enclosing the key or value in double quotes)
...
Afterwards I played a little bit with the files in the mentioned: app/target/universal/stage/conf/ folder and I get that it's like some script (or config) from Heroku/ or from the app complains when other files different than the application.conf file exists. Actually, when I started deleting them in the server side and re-copile the app the log shows me the same error with other filenames: logback.xml, messages, routes, that are in the conf folder of the app.  It's the first time I got this behavior with a play app , may be something is changed when we combined nodejs/ruby/play deploy. 
Any suggestions to solve this issue?? There is another way to deploy the app that I'm missing? 

I also tried the Heroku deploy button that you add in the readme file..  the deploy process is similar the obtained with tollbelt, and similarly when I opened the app (done everything from web) I also get an App Error.
Thanks for any help.

**Comment by akkie** [comment]
Have you specified the `PLAY_CONF_FILE` variable for your application? This variable must have the value `application.prod.conf`.

**Comment by renexdev** [comment]
OK I see... Its like heroku doen't read the setting in the file "app.json". In the case of the "NPM_CONFIG_PRODUCTION" setting, inspite its in the env of the config file I had to set with "heroku config:set NPM_CONFIG_PRODUCTION=false" from toolbelt command line. This afternoon I'll tell you. Thanks!

**Comment by renexdev** [comment]
Capo akkie!  You need to set in heroku toolbelt:
heroku config:set PLAY_CONF_FILE=application.prod.conf
heroku config:set PLAY_APP_SECRET=micodigosupersecreto
and works! |
Now I can start working in my app with this base template. I have to learn more on angularjs before =).
The only question that remains in the inkwell is why the "app.json" settings are not taken by heroku, koz all the setting you have to write down are already in there. Anyway this solves my issue, thanks again!
Cheers !
ReneX
