### ISSUE TITLE
I have NO info on http://localhost:9000/

### ISSUE THREAD

**Issue by jsdevelopcom** [mohiva/play-silhouette-angular-seed#33]
During import in IntelliJ IDEA 15, I have some problems:

SBT project import

[warn] There may be incompatibilities among your library dependencies. [warn] Here are some of the libraries that were evicted: [warn] * org.webjars:jquery:(1.11.0, 1.11.1, 1.9.0) -> 2.1.4 [warn] Run 'evicted' to see detailed eviction warnings [warn] [FAILED ] com.typesafe.sbt#sbt-scalariform;1.3.0!sbt-scalariform.jar(src): (0ms) [warn] ==== typesafe-ivy-releases: tried [warn] https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-scalariform/scala_2.10/sbt_0.13/1.3.0/srcs/sbt-scalariform-sources.jar [warn] ==== sbt-plugin-releases: tried [warn] https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-scalariform/scala_2.10/sbt_0.13/1.3.0/srcs/sbt-scalariform-sources.jar [warn] ==== local: tried [warn] C:\Users\win8.1\.ivy2\local\com.typesafe.sbt\sbt-scalariform\scala_2.10\sbt_0.13\1.3.0\srcs\sbt-scalariform-sources.jar [warn] ==== public: tried [warn] https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-scalariform_2.10_0.13/1.3.0/sbt-scalariform-1.3.0-sources.jar [warn] ==== Typesafe repository: tried [warn] http://repo.typesafe.com/typesafe/releases/com/typesafe/sbt/sbt-scalariform_2.10_0.13/1.3.0/sbt-scalariform-1.3.0-sources.jar [warn] ==== Sonatype snapshots: tried [warn] https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/sbt/sbt-scalariform_2.10_0.13/1.3.0/sbt-scalariform-1.3.0-sources.jar [warn] ==== Scalaz Bintray: tried [warn] https://dl.bintray.com/scalaz/releases/com/typesafe/sbt/sbt-scalariform_2.10_0.13/1.3.0/sbt-scalariform-1.3.0-sources.jar [warn] :::::::::::::::::::::::::::::::::::::::::::::: [warn] :: FAILED DOWNLOADS :: [warn] :: ^ see resolution messages for details ^ :: [warn] :::::::::::::::::::::::::::::::::::::::::::::: [warn] :: com.typesafe.sbt#sbt-scalariform;1.3.0!sbt-scalariform.jar(src) [warn] ::::::::::::::::::::::::::::::::::::::::::::::

+

"C:\Program Files\Java\jdk1.8.0_66\bin\java" -Dfile.encoding=UTF8 -Djline.terminal=none -Dsbt.log.noformat=true -Dsbt.global.base=C:\Users\win8.1\AppData\Local\Temp\sbt-global-plugin0stub -Xms512M -Xmx1024M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M -classpath C:\Users\win8.1\.IntelliJIdea15\config\plugins\Scala\launcher\sbt-launch.jar xsbt.boot.Boot "project root" run
[info] Loading project definition from C:\Examples\PLAY2\play-silhouette-angular-seed\project
[info] Set current project to play-silhouette-angular-seed (in build file:/C:/Examples/PLAY2/play-silhouette-angular-seed/)
[info] Set current project to play-silhouette-angular-seed (in build file:/C:/Examples/PLAY2/play-silhouette-angular-seed/)
[info] Updating {file:/C:/Examples/PLAY2/play-silhouette-angular-seed/}root...
[info] Resolving org.scala-lang#scala-compiler;2.11.7 ...
[info] Resolving org.scala-lang#scala-library;2.11.7 ...
[info] Resolving org.scala-lang#scala-reflect;2.11.7 ...
[info] Resolving org.scala-lang.modules#scala-xml_2.11;1.0.4 ...
[info] Resolving org.scala-lang.modules#scala-parser-combinators_2.11;1.0.4 ...
[info] Resolving com.typesafe.play#twirl-api_2.11;1.1.1 ...
[info] Resolving org.apache.commons#commons-lang3;3.4 ...
[info] Resolving com.typesafe.play#play-server_2.11;2.4.2 ...
[info] Resolving com.typesafe.play#play_2.11;2.4.2 ...
[info] Resolving com.typesafe.play#build-link;2.4.2 ...
[info] Resolving com.typesafe.play#play-exceptions;2.4.2 ...
[info] Resolving org.javassist#javassist;3.19.0-GA ...
[info] Resolving com.typesafe.play#play-iteratees_2.11;2.4.2 ...
[info] Resolving org.scala-stm#scala-stm_2.11;0.7 ...
[info] Resolving com.typesafe#config;1.3.0 ...
[info] Resolving com.typesafe.play#play-json_2.11;2.4.2 ...
[info] Resolving com.typesafe.play#play-functional_2.11;2.4.2 ...
[info] Resolving com.typesafe.play#play-datacommons_2.11;2.4.2 ...
[info] Resolving joda-time#joda-time;2.8.1 ...
[info] Resolving org.joda#joda-convert;1.7 ...
[info] Resolving com.fasterxml.jackson.core#jackson-core;2.5.4 ...
[info] Resolving com.fasterxml.jackson.core#jackson-annotations;2.5.4 ...
[info] Resolving com.fasterxml.jackson.core#jackson-databind;2.5.4 ...
[info] Resolving com.fasterxml.jackson.datatype#jackson-datatype-jdk8;2.5.4 ...
[info] Resolving com.fasterxml.jackson.datatype#jackson-datatype-jsr310;2.5.4 ...
[info] Resolving com.typesafe.play#play-netty-utils;2.4.2 ...
[info] Resolving org.slf4j#slf4j-api;1.7.12 ...
[info] Resolving org.slf4j#jul-to-slf4j;1.7.12 ...
[info] Resolving org.slf4j#jcl-over-slf4j;1.7.12 ...
[info] Resolving ch.qos.logback#logback-core;1.1.3 ...
[info] Resolving ch.qos.logback#logback-classic;1.1.3 ...
[info] Resolving com.typesafe.akka#akka-actor_2.11;2.3.11 ...
[info] Resolving com.typesafe.akka#akka-slf4j_2.11;2.3.11 ...
[info] Resolving commons-codec#commons-codec;1.10 ...
[info] Resolving xerces#xercesImpl;2.11.0 ...
[info] Resolving xml-apis#xml-apis;1.4.01 ...
[info] Resolving javax.transaction#jta;1.1 ...
[info] Resolving com.google.inject#guice;4.0 ...
[info] Resolving javax.inject#javax.inject;1 ...
[info] Resolving aopalliance#aopalliance;1.0 ...
[info] Resolving com.google.guava#guava;16.0.1 ...
[info] Resolving com.google.inject.extensions#guice-assistedinject;4.0 ...
[info] Resolving com.google.inject.extensions#guice-assistedinject;4.0 ...
[info] Resolving com.google.inject.extensions#extensions-parent;4.0 ...
[info] Resolving com.typesafe.play#play-netty-server_2.11;2.4.2 ...
[info] Resolving io.netty#netty;3.10.3.Final ...
[info] Resolving com.typesafe.netty#netty-http-pipelining;1.1.4 ...
[info] Resolving com.mohiva#play-silhouette_2.11;3.0.0 ...
[info] Resolving com.typesafe.play#play-cache_2.11;2.4.2 ...
[info] Resolving net.sf.ehcache#ehcache-core;2.6.11 ...
[info] Resolving com.typesafe.play#play-ws_2.11;2.4.2 ...
[info] Resolving com.google.guava#guava;18.0 ...
[info] Resolving com.ning#async-http-client;1.9.21 ...
[info] Resolving oauth.signpost#signpost-core;1.2.1.2 ...
[info] Resolving oauth.signpost#signpost-commonshttp4;1.2.1.2 ...
[info] Resolving org.apache.httpcomponents#httpcore;4.0.1 ...
[info] Resolving org.apache.httpcomponents#httpclient;4.0.1 ...
[info] Resolving commons-logging#commons-logging;1.1.1 ...
[info] Resolving org.mindrot#jbcrypt;0.3m ...
[info] Resolving com.atlassian.jwt#jwt-core;1.2.4 ...
[info] Resolving com.nimbusds#nimbus-jose-jwt;2.16 ...
[info] Resolving net.jcip#jcip-annotations;1.0 ...
[info] Resolving net.minidev#json-smart;1.1.1 ...
[info] Resolving javax.mail#mail;1.4.7 ...
[info] Resolving javax.activation#activation;1.1 ...
[info] Resolving org.bouncycastle#bcprov-jdk15on;1.51 ...
[info] Resolving com.atlassian.jwt#jwt-api;1.2.4 ...
[info] Resolving com.google.code.findbugs#jsr305;2.0.1 ...
[info] Resolving org.webjars#webjars-play_2.11;2.4.0 ...
[info] Resolving org.webjars#requirejs;2.1.15 ...
[info] Resolving org.webjars#webjars-locator;0.23 ...
[info] Resolving org.webjars#webjars-locator-core;0.22 ...
[info] Resolving org.webjars#bootstrap;3.1.1 ...
[info] Resolving org.webjars#jquery;1.11.0 ...
[info] Resolving net.codingwell#scala-guice_2.11;4.0.0 ...
[info] Resolving com.google.inject.extensions#guice-multibindings;4.0 ...
[info] Resolving com.google.inject.extensions#guice-multibindings;4.0 ...
[info] Resolving com.google.inject.extensions#extensions-parent;4.0 ...
[info] Resolving net.ceedubs#ficus_2.11;1.1.2 ...
[info] Resolving com.adrianhurt#play-bootstrap3_2.11;0.4.4-P24 ...
[info] Resolving org.webjars#jquery;2.1.4 ...
[info] Resolving org.webjars#bootstrap;3.3.4 ...
[info] Resolving com.typesafe.play#filters-helpers_2.11;2.4.2 ...
[info] Resolving com.tuplejump#play-yeoman_2.11;0.8.1 ...
[info] Resolving com.typesafe.play#play-test_2.11;2.4.2 ...
[info] Resolving junit#junit;4.12 ...
[info] Resolving org.hamcrest#hamcrest-core;1.3 ...
[info] Resolving com.novocode#junit-interface;0.11 ...
[info] Resolving org.scala-sbt#test-interface;1.0 ...
[info] Resolving com.google.code.findbugs#jsr305;2.0.3 ...
[info] Resolving org.fluentlenium#fluentlenium-core;0.10.3 ...
[info] Resolving org.seleniumhq.selenium#selenium-java;2.44.0 ...
[info] Resolving org.seleniumhq.selenium#selenium-chrome-driver;2.44.0 ...
[info] Resolving org.seleniumhq.selenium#selenium-remote-driver;2.44.0 ...
[info] Resolving cglib#cglib-nodep;2.1_3 ...
[info] Resolving com.google.code.gson#gson;2.3 ...
[info] Resolving org.seleniumhq.selenium#selenium-api;2.44.0 ...
[info] Resolving org.apache.httpcomponents#httpclient;4.3.4 ...
[info] Resolving org.apache.httpcomponents#httpcore;4.3.2 ...
[info] Resolving commons-logging#commons-logging;1.1.3 ...
[info] Resolving org.apache.commons#commons-exec;1.1 ...
[info] Resolving net.java.dev.jna#jna;3.4.0 ...
[info] Resolving net.java.dev.jna#platform;3.4.0 ...
[info] Resolving org.seleniumhq.selenium#selenium-htmlunit-driver;2.44.0 ...
[info] Resolving net.sourceforge.htmlunit#htmlunit;2.15 ...
[info] Resolving xalan#xalan;2.7.1 ...
[info] Resolving xalan#serializer;2.7.1 ...
[info] Resolving commons-collections#commons-collections;3.2.1 ...
[info] Resolving org.apache.httpcomponents#httpmime;4.3.3 ...
[info] Resolving net.sourceforge.htmlunit#htmlunit-core-js;2.15 ...
[info] Resolving net.sourceforge.nekohtml#nekohtml;1.9.21 ...
[info] Resolving net.sourceforge.cssparser#cssparser;0.9.14 ...
[info] Resolving org.w3c.css#sac;1.3 ...
[info] Resolving commons-io#commons-io;2.4 ...
[info] Resolving org.eclipse.jetty#jetty-websocket;8.1.15.v20140411 ...
[info] Resolving org.eclipse.jetty#jetty-util;8.1.15.v20140411 ...
[info] Resolving org.eclipse.jetty#jetty-io;8.1.15.v20140411 ...
[info] Resolving org.eclipse.jetty#jetty-http;8.1.15.v20140411 ...
[info] Resolving org.seleniumhq.selenium#selenium-firefox-driver;2.44.0 ...
[info] Resolving org.seleniumhq.selenium#selenium-ie-driver;2.44.0 ...
[info] Resolving org.seleniumhq.selenium#selenium-safari-driver;2.44.0 ...
[info] Resolving org.webbitserver#webbit;0.4.14 ...
[info] Resolving org.seleniumhq.selenium#selenium-support;2.44.0 ...
[info] Resolving com.mohiva#play-silhouette-testkit_2.11;3.0.0 ...
[info] Resolving junit#junit;4.11 ...
[info] Resolving com.typesafe.play#play-omnidoc_2.11;2.4.2 ...
[info] Resolving org.scala-lang#scala-library;2.11.6 ...
[info] Resolving com.typesafe.play#play-docs_2.11;2.4.2 ...
[info] Resolving org.scala-lang#scala-reflect;2.11.6 ...
[info] Resolving org.scala-lang.modules#scala-xml_2.11;1.0.1 ...
[info] Resolving org.scala-lang.modules#scala-parser-combinators_2.11;1.0.1 ...
[info] Resolving com.typesafe.play#play-doc_2.11;1.2.2 ...
[info] Resolving org.pegdown#pegdown;1.4.0 ...
[info] Resolving org.parboiled#parboiled-java;1.1.5 ...
[info] Resolving org.parboiled#parboiled-core;1.1.5 ...
[info] Resolving org.ow2.asm#asm;4.1 ...
[info] Resolving org.ow2.asm#asm-tree;4.1 ...
[info] Resolving org.ow2.asm#asm-analysis;4.1 ...
[info] Resolving org.ow2.asm#asm-util;4.1 ...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* org.webjars:jquery:(1.11.0, 1.11.1, 1.9.0) -> 2.1.4
[warn] Run 'evicted' to see detailed eviction warnings

--- (Running the application, auto-reloading is enabled) ---

[info] p.a.l.c.ActorSystemProvider - Starting application default Akka system: application
[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
'force' enabled
Will run: [cmd, /c, grunt, --gruntfile=Gruntfile.js, watch, --force] in C:\Examples\PLAY2\play-silhouette-angular-seed\ui

Server started, use Alt+D to stop

"grunt" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
[info] Compiling 27 Scala sources and 2 Java sources to C:\Examples\PLAY2\play-silhouette-angular-seed\target\scala-2.11\classes...
[info] p.a.l.c.ActorSystemProvider - Starting application default Akka system: application
[info] play.api.Play - Application started (Dev)

= 

blank http://localhost:9000/

**Comment by akkie** [comment]
Please could you remove the scalariform plugin and config from your build files? Do you have all the JS build dependencies installed?

**Comment by akkie** [comment]
Does it work if you following the getting started guide?

**Comment by jsdevelopcom** [comment]
Should I delete some plugins in IntelliJ IDEA?

**Comment by akkie** [comment]
This has nothing to do with your IDE. The scalariform plugin is a SBT plugin which is defined in `projects/plugins.sbt` and configured in `build.sbt`. You must also have `yo', 'grunt', 'grunt-cli', and 'bower` installed on your machine. This is all documented in the [readme](https://github.com/mohiva/play-silhouette-angular-seed#getting-started).

**Comment by akkie** [comment]
Is the problem solved?

**Comment by jsdevelopcom** [comment]
I`ve use  IntelliJ IDEA 15.0.3 in Windows 10

**Comment by akkie** [comment]
Have you tried my suggested changes? Do you followed the getting started guide I've linked?
