### ISSUE TITLE
Could you include some test for routes and controllers using ScalaTest + Play?

### ISSUE THREAD

**Issue by shafiquejamal** [mohiva/play-silhouette-angular-seed#35]
The related project 

https://github.com/mohiva/play-silhouette-seed/

has some tests, though using Spec2. I tried adding some tests for routes, but I'm getting Guice errors, which I have described here:

https://stackoverflow.com/questions/36273934/testing-a-route-in-play-in-a-controller-using-guice-dependency-injection-error

Thanks,

**Comment by akkie** [comment]
No sorry. If ever then I will include only Specs2 tests.

**Comment by phancox** [comment]
shafiquejamal,

Did you ever manage to get scalatest working for play-silhouette.  Struggling to get this working at present so any hints would be greatly appreciated.

THANKS

**Comment by shafiquejamal** [comment]
Hello Peter,

No, I couldn't get this working. I even asked a couple of people for help and they couldn't do it either. If I ever get ScalaTest tests working for the routes and controllers, I'll post here about it. If you get them working, could you please do so as well? Good luck!

**Comment by phancox** [comment]
Thanks Shafique,

Pretty new to this so if more experienced players haven't been able to crack it, then it's not looking good for me.  But will post back if I have any luck.

**Comment by phancox** [comment]
Hi Shafique

Attached is what I came up with; based on the play-silhouette-seed template and slightly modified to match my code.  But at least it works in scalatest.

```
package controllers

import org.scalatestplus.play._
import play.api.test._
import play.api.test.Helpers._
import play.api.libs.concurrent.Execution.Implicits._
import play.api.inject.guice.GuiceApplicationBuilder
import net.codingwell.scalaguice.ScalaModule
import com.google.inject.AbstractModule
import com.mohiva.play.silhouette.api.{Environment, LoginInfo}
import com.mohiva.play.silhouette.test._
import org.joda.time.LocalDate
import utils.auth.DefaultEnv
import models.Person

class ApplicationControllerSpec extends PlaySpec with OneAppPerSuite {
 
  class FakeModule extends AbstractModule with ScalaModule {
    def configure() = {
      bind[Environment[DefaultEnv]].toInstance(env)
    }
  }

  val identity = Person("","",new LocalDate)

  implicit val env: Environment[DefaultEnv] = new FakeEnvironment[DefaultEnv](Seq(LoginInfo("credentials","admin@example.com") -> identity))

  implicit override lazy val app = new GuiceApplicationBuilder()
      .overrides(new FakeModule)
      .build()
  
  "Routes" should {
    "return 404 on a bad request" in  {
      val homePage = route(app, FakeRequest(GET, "/badrequest")).get
      status(homePage) mustBe NOT_FOUND
    }
  }

  "ApplicationController" should {
    "redirect to signin page when no user signed in" in {
      val indexResult = route(app, FakeRequest(GET, "/")).get
      status(indexResult) mustBe SEE_OTHER
      val redirectUrl = redirectLocation(indexResult).getOrElse("") 
      redirectUrl mustBe routes.SignInController.view().toString
      val redirectResult = route(app, FakeRequest(GET, redirectUrl)).get
      status(redirectResult) mustBe OK
      contentType(redirectResult) mustBe Some("text/html")
      contentAsString(redirectResult) must include ("Sign in with your credentials")
    }
  }

  "ApplicationController" should {
    "redirect to signin page with unknown user" in {
      val request = FakeRequest(GET, "/").withAuthenticator[DefaultEnv](LoginInfo("credentials","noone@example.com"))
      val result = route(app, request).get
      status(result) mustBe SEE_OTHER
      redirectLocation(result) mustBe Some(routes.SignInController.view().toString)
    }
  }

  "ApplicationController" should {
    "access home page when user signed in" in {
      val request = FakeRequest(GET, "/").withAuthenticator[DefaultEnv](LoginInfo("credentials","admin@example.com"))
      val result = route(app, request).get
      status(result) mustBe OK
    }
  }
}

```

**Comment by shafiquejamal** [comment]
Hello Peter,

Thanks for sending this. I found something similar here:

[http://www.michaelpollmeier.com/2015/09/25/playframework-guice-di](http://www.michaelpollmeier.com/2015/09/25/playframework-guice-di)

Which I am using in a for-fun project here:

[https://github.com/shafiquejamal/play-authentication](https://github.com/shafiquejamal/play-authentication)

Cheers,
