### ISSUE TITLE
The token is getting invalidated every time I restart the server. 

### ISSUE THREAD

**Issue by ajaygeorge91** [mohiva/play-silhouette-angular-seed#36]
The JWT token is getting invalidated every time I restart the server. Is there anyway to persist the already issued tokens

**Comment by akkie** [comment]
Please do not ask questions in the issue tracker. Please read https://github.com/mohiva/play-silhouette#support.

Anyway, I've [answered](https://groups.google.com/forum/#!topic/play-silhouette/s65vP3mk1To) this question some days ago.
