### ISSUE TITLE
bower install error

### ISSUE THREAD

**Issue by nanothermite** [mohiva/play-silhouette-angular-seed#37]
gives me this:

Stack trace:
Error: EEXIST: file already exists, open '/home/hkatz/.cache/bower/packages/35300e45e44dbc6f186ed069533ef0af-2.2.3.lock'
    at Error (native)

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/lib/bin/bower.js:110:26)
    at emitOne (events.js:90:13)
    at Logger.emit (events.js:182:7)
    at Logger.emit (/usr/local/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)
System info:
Bower version: 1.7.9
Node version: 5.10.1
OS: Linux 2.6.32-573.22.1.el6.x86_64 x64

even after I try bower cache clean in shell prior to running sbt. Just updated git to this last play 2.5.2 release. This is Centos 6.7.

Please advise.

Thanks

**Comment by akkie** [comment]
@OliverKK :+1: 

This is the Heroku build log:
```
-----> Fetching set buildpack https://github.com/heroku/heroku-buildpack-multi... done
-----> Multipack app detected
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-ruby.git
=====> Detected Framework: Ruby
-----> Compiling Ruby
-----> Using Ruby version: ruby-2.3.0
-----> Installing dependencies using bundler 1.11.2
       Your app was upgraded to bundler 1.11.2.
       Previously you had a successful deploy with bundler 1.9.7.
       
       If you see problems related to the bundler version please refer to:
       https://devcenter.heroku.com/articles/bundler-version
       Ruby version change detected. Clearing bundler cache.
       Old: ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
       New: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       You are trying to install in deployment mode after changing
       your Gemfile. Run `bundle install` elsewhere and add the
       updated Gemfile.lock to version control.
       You have added to the Gemfile:
       * sass (= 3.4.22)
       You have deleted from the Gemfile:
       * sass (= 3.4.9)
       Bundler Output: You are trying to install in deployment mode after changing
       your Gemfile. Run `bundle install` elsewhere and add the
       updated Gemfile.lock to version control.
       
       You have added to the Gemfile:
       * sass (= 3.4.22)
       
       You have deleted from the Gemfile:
       * sass (= 3.4.9)
 !
 !     Failed to install gems via Bundler.
 !
 !     Push rejected, failed to compile Multipack app
```

Maybe the [build pack](https://github.com/heroku/heroku-buildpack-multi) has updated in the meantime? If you create a Heroku account, then you can test it.

**Comment by akkie** [comment]
It seems that the `Gemfile.lock` is the old one. This should also be updated.

```
Bundler Output: You are trying to install in deployment mode after changing
       your Gemfile. Run `bundle install` elsewhere and add the
       updated Gemfile.lock to version control.

       You have added to the Gemfile:
       * sass (= 3.4.22)

       You have deleted from the Gemfile:
       * sass (= 3.4.9)
```

**Comment by OliverKK** [comment]
@akkie I´am looking into that. Thanks.

**Comment by nanothermite** [comment]
Update, I had resolved my bower build. Outside of sbt (or activator), I ran the npm install after clearing both its and bower cache. I also had to update system version of rvm as well as ruby to 2.3.0. I also manually inspected the index.html in ui to ensure npm had all the angular variants required else the first request to the controller would show j/s errors in the browser developer tool.

**Comment by OliverKK** [comment]
I did create a new Gemfile.lock by executing `bundle install` and pushing it to my heroku repo.
Still the same error:

You have added to the Gemfile:
remote:        * sass (= 3.4.22)
remote:        
remote:        You have deleted from the Gemfile:
remote:        * sass (= 3.4.9)

Revoking changes to sass 3.4.9 didn´t have a effect either.

**Comment by akkie** [comment]
Could you nevertheless push the updated `Gemfile.lock`?

**Comment by OliverKK** [comment]
@see PR #38

**Comment by akkie** [comment]
The build runs now fine on Heroku
