### ISSUE TITLE
Blank root "GET /" for Heroku deployment

### ISSUE THREAD

**Issue by apatzer** [mohiva/play-silhouette-angular-seed#44]
On a local deployment, this angular seed works just fine: I can see localhost:9000/, sign-in, etc. However, deploying to Heroku with the "Deploy on Heroku" button gives a blank page: Not Found for 'GET /'

The system is deployed correctly, and the logs show Node.Js, a Yeoman sanity check, and all bower components being installed.

A call to /user gives "Not Authenticated" indicating the JSON APIs are up and running. To me this indicates a "routes" problem, perhaps with Yeoman.

```
GET         /                                com.tuplejump.playYeoman.Yeoman.index
->          /                                yeoman.Routes
```

I've tried adding a "grunt build" to the package.json scripts, which runs grunt, but still gives me a blank page.

```
"scripts": {
    "postinstall": "cd ui && npm install && bower install && grunt build"
  }
```

Any suggestions? Again, works fine locally, and the Heroku logs don't give me any errors.

**Comment by apatzer** [comment]
This seems to be the case for your master deployment as well... http://play-silhouette-angular-seed.herokuapp.com/

**Comment by akkie** [comment]
I'm aware of this issue and I think it has to do with https://github.com/tuplejump/play-yeoman/issues/95

**Comment by akkie** [comment]
Fixed with the workaround posted in https://github.com/tuplejump/play-yeoman/issues/95#issuecomment-233626696
