### ISSUE TITLE
Multiple transactions may cause DB inconsistencies in SignupController.scala

### ISSUE THREAD

**Issue by geirhe** [mohiva/play-silhouette-angular-seed#6]
I have been looking at silhouette the last few months.

Line 58, or thereabouts:

```scala
   for {
      user <- userService.save(user)
      authInfo <- authInfoService.save(loginInfo, authInfo)
      authenticator <- env.authenticatorService.create(loginInfo)
      token <- env.authenticatorService.init(authenticator)
    } yield {
```

The service calls in this for thingy all produce futures, and save bits of the authentication info in separate transactions. If two queries arrive simultaneously, the scheduling of threads will affect which bits get to be processed first.

My personal opinion is that the futures in use here do not make much sense. Most database drivers are blocking, and trading off transactional integrity for an uncertain amount of parallelism seems like a design choice that could perhaps be improved? If there is something here I don't see I would love to learn.

I think there should be a clear transactional boundary in the controller when it starts reading or writing. If part of the request is meant to be asynchronous I would like to see some kind of error handling outside what is presented to the user if something breaks - a log entry, at least.

I can help if we agree that this is a problem.

**Comment by akkie** [comment]
Hi,

Thanks for your interest in Silhouette. But I think there can't be a race condition here. The for comprehension is syntactic sugar for `Future.map` and `Future.flatMap` calls. It can also be written:

```scala
userService.save(user).flatMap { user =>
  authInfoService.save(loginInfo, authInfo).flatMap { => authInfo
    ...
  }
}
```
So you can see that the subsequently calls are all executed in a sequential manner.

Silhouette is a reactive library and therefore all components must be reactive. Your suggested problem of blocking database drivers isn't a design flaw of Silhouette itself, but rather a fault of the database vendors. Currently there exists some async database drivers and the long-term trend is async. I think the next slick version is also async. You can also use futures inside a database transaction. We use this in our company with slick and it works very well.

This seed template is only an example to show how individual pieces fit together. You can also create a service which stores all your data. This can use a transaction to save the individual parts.

**Comment by geirhe** [comment]
The issue here is not the for comprehension itself. It is of the save methods returning a Future. The future is going to be completed on another thread, which means that there are no currently known technologies that allow me to link the UserService.save transaction to the auth.save transaction.

I would suggest that forcing me to leave the database in an inconsistent state if one of the futures fails (due to the signature of the save method, which is part of silhouette) is a design flaw with silhouette. From the perspective of one who would have to handle the support side, it is a huge problem since it causes the kind of problem that would force someone to manually clean up the database. Manually tweaking the database is extremely costly, and worse, bound to cause outages over time.

**Comment by akkie** [comment]
Correct my if I'm wrong, but you can share a database connection among threads. So if you start a transaction in the main thread you can pass it to your child threads. Now if the future completes you can commit the transaction on this connection and if the future fails you can rollback the transaction on this connection. As noted above, we do this in a live application and we haven't encountered any issues so far.

If you take a look at the [PostgresAsync](https://github.com/mauricio/postgresql-async#transactions) driver then you can see that transactions are possible with futures.

An other example from the [ScalikeJDBC-Async driver](https://github.com/scalikejdbc/scalikejdbc-async)

```scala
// create a new record within a transaction
val created: Future[Company] = AsyncDB.localTx { implicit tx =>
  for {
    company <- Company.create("ScalikeJDBC, Inc.", Some("http://scalikejdbc.org/"))
    seratch <- Programmer.create("seratch", Some(company.id))
    gakuzzzz <- Programmer.create("gakuzzzz", Some(company.id))
    xuwei_k <- Programmer.create("xuwei-k", Some(company.id))
  } yield company
}
```

Do I miss something?

**Comment by geirhe** [comment]
I can do that, sure, except for the signature of AuthInfoService.save. It differs from the signature in the above ScalikeJDBC-Async example by not making provisions for passing along a session/transaction. Quoth the code (Company):

```scala
 def create(name: String, url: Option[String] = None, createdAt: DateTime = DateTime.now)(
implicit session: AsyncDBSession = AsyncDB.sharedSession, cxt: EC = ECGlobal): Future[Company] = {
``` 
AuthInfoService:
```scala
 def save[T <: AuthInfo](loginInfo: LoginInfo, authInfo: T): Future[T]
```

I can either pass along an implicit or explicit transaction, or I can use something like the dynTransaction in Slick which places the transaction in a threadlocal variable. The first approach sullies the interfaces with transactional semantics and locks the user of the interface to using the persistence framework mentioned in the signature, the other requires units of work/transactions to be handled within a thread.

As I read the save method on AuthInfoService, you are forcing me to jump threads by requiring the return of a future, and there are no provisions for passing along a transaction. Please tell me if I have missed something.

I have no beef with the retrieve method. It makes sense that retrieving an auth object should complete inside a single transaction. I also like being able to use a different persistence style than what your example uses.

My personal opinion is that service interfaces, such as AuthInfoService, should not meddle in these things. Services should be composable by the user, which means they, amongst other things, should not force specific handling of transactions, security, logging or asynchronicity with their client. I would like the client to decide these things.

**Comment by akkie** [comment]
You can have another save method with another signature in your service. The method you mentioned is needed by Silhouette to [store](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/impl/providers/CredentialsProvider.scala#L68) the auth information in the credential based providers after the password algorithm was changed.

**Comment by geirhe** [comment]
Yes, this is true. I can rewrite the example you provide.

**Comment by akkie** [comment]
Can this then be closed?

**Comment by geirhe** [comment]
If you are happy with the example, by all means close this issue.

**Comment by akkie** [comment]
I'm happy, but I've asked you (o; If you have a concrete improvement proposal then I would be happy to hear that.

**Comment by geirhe** [comment]
Well, examples such as the one you have provided (good job, by the way) shapes a lot of projects if whatever they are an example for actually sees mainstream use. The old codgers won't use example projects, but a lot of younger, more inexperienced developers might.

And that is where I think inconsistencies and error handling is important. Not because it is important in the authentication parts of an application, but because the controllers and services you provide might just become a template for all the other controllers and services in a new application. For better or worse, you are setting an example.

So no, I don't think this issue should be closed.

I think the for goodness should either get
- a comment stating "multiple transactions, if one fails will leave inconsistent database, logs must be monitored for db errors so any inconsistencies can get sorted out manually"
- or introduction of logging that makes it easier to detect inconsistent database statuses, with the "here be multiple transactions" comment
- or a rewrite to handle using one transaction across the existing futures (not my preferred solution because I have a healthy dollop of respect of sending mutable data across futures/actors/threads - a live transaction seems to me to be a prime example of mutable state. I need a very good reason to attempt to do so. I don't see one here.)
- or a rewrite to handle signup using one transaction in one thread (my personal preferred solution). To my mind, this would be a non-futuristic save method. The existing save method should get a comment about being used to swap the credentials in-flight during login if the preferred encrypton algorithm has changed. This is a bit of magic not many authentication libraries provide.

**Comment by akkie** [comment]
Thanks for your answer. I think what we can do for this example is to create a comment in the README that describes the spirit and purpose of this example. Something like this:

This example tries to show how the single pieces of Silhouette works together and nothing more. It provides a small foundation which can be used(without a lot of work) to adapt the example to its own use case. As with the [Silhouette Seed](https://github.com/mohiva/play-silhouette-seed) example, there can be other examples which acts as examples for concrete use cases.

Please keep in mind that relational databases are not the only way to store data. There exists other storage systems and we cannot cover all the possible use cases. This example doesn't also exists to teach developers best practices for other technologies.

As noted above we can have another example which shows how transactions can be implemented with a relational database. Would you implement such an example? You could take a look at the [Slick Seed](https://github.com/sne11ius/play-silhouette-slick-seed) example.

**Comment by geirhe** [comment]
That works for me.

As for me implementing another example: sure, but there is a major problem. I don't know Slick - yet. Trying to get there, though.
