### ISSUE TITLE
Exception when trying to authenticate with Google

### ISSUE THREAD

**Issue by jptissot** [mohiva/play-silhouette-angular-seed#8]
Hi, I am getting this exception when trying to authenticate with Google. 

```
[error] c.SocialAuthController - Unexpected provider error
com.mohiva.play.silhouette.impl.exceptions.UnexpectedResponseException: [Silhouette][google] Cannot build OAuth2Info because of invalid response format: List((/access_token,List(ValidationError(error.path.missing,Wra
ppedArray()))))
        at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:162) ~[play-silhouette_2.11-2.0-RC2.jar:2.0-RC2]
        at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$buildInfo$1.apply(OAuth2Provider.scala:162) ~[play-silhouette_2.11-2.0-RC2.jar:2.0-RC2]
        at scala.util.Either.fold(Either.scala:98) ~[scala-library-2.11.6.jar:na]
        at com.mohiva.play.silhouette.impl.providers.OAuth2Provider.buildInfo(OAuth2Provider.scala:161) ~[play-silhouette_2.11-2.0-RC2.jar:2.0-RC2]
        at com.mohiva.play.silhouette.impl.providers.OAuth2Provider$$anonfun$getAccessToken$2.apply(OAuth2Provider.scala:150) ~[play-silhouette_2.11-2.0-RC2.jar:2.0-RC2]
```

Please let me know if you need any additional information about the issue. I'm using the latest RC2. 
I have updated the Google tokens in the app.json and app.js.

**Comment by akkie** [comment]
Do you have configure your Google application to allow redirects from your URL?

**Comment by jptissot** [comment]
I have tried to set it to http://localhost:9000, http://localhost, http://localhost:9000/authenticate without success. How do you configure it to work on your local development server. 

I think printing our the response in the exception message would help to debug. I am unsure of where to do this as I am new to scala.

**Comment by akkie** [comment]
I've http://localhost:9000 as redirect URI and JavaScript source. You must configure the client ID in the silhouette.conf and the app.js. And also the client secret in the silhouette.conf.

You could debug your application and set a breakpoint to watch the response body. But I think it would be nice to have a debug statement for the response boy too. The problem here is that if a user configures the application to log all debug messages in production, then all access tokens will be logged. Which is really bad.

**Comment by jptissot** [comment]
I completely agree with you that this debugging information should not be in the exception as it's a security risk for users. The only thing you mentioned that I did not try is to put localhoat:9000 in the Javascript source. I will try that out and let you know the results.

**Comment by jptissot** [comment]
I tried a couple more things but I still get this exception.
Here are my google settings : 
![image](https://cloud.githubusercontent.com/assets/4681586/6765227/15937e98-cfad-11e4-8e6f-74d4c07a33b4.png)

Here is the config in my app.js 
![image](https://cloud.githubusercontent.com/assets/4681586/6765228/273bad1e-cfad-11e4-96ef-3fc467440897.png)


Here is my env app.json
![image](https://cloud.githubusercontent.com/assets/4681586/6765231/49e194e6-cfad-11e4-9aff-23d00aed3a38.png)


Herre is my google config in silhouette.conf (unchanged) 
![image](https://cloud.githubusercontent.com/assets/4681586/6765241/0840f8b4-cfae-11e4-844d-2875c383cc4c.png)

**Comment by akkie** [comment]
Do you try to login from an app hosted on Heroku or on localhost?

**Comment by jptissot** [comment]
I tried the example hosted app and everything works fine. It's when I try using localhost that it fails with the exception mentionned above. Can i provide you anything else to help debug ? 
One thing I noticed is that the authenticate method of the SocialAuthController is being called twice. not sure if that is normal or not.

**Comment by jptissot** [comment]
Seems I am not the only one getting this exception. Look at the comment of this page: https://typesafe.com/activator/template/play-silhouette-angular-seed 

Here is what is displayed in IntelliJ when I debug the project.

![image](https://cloud.githubusercontent.com/assets/4681586/6766284/b997c854-cfd6-11e4-8f5b-85dd51a5cadb.png)

**Comment by jptissot** [comment]
One thing I just noticed is that the env setting is set to   "PLAY_CONF_FILE": "application.prod.conf"  instead of application.conf. Do I need to rebuild the project for the setting to be applied if I change it  ?

**Comment by akkie** [comment]
The double request is a bug in [Satellizer](https://github.com/sahat/satellizer/issues/287) but this isn't a problem for Google, Facebook or Twitter. I've now tested the application from localhost and for me it works as expected. I think you have a problem with your configuration. The app.json doesn't work on localhost. This is an Heroku specific file. Either you set environment variables with your `GOOGLE_CLIENT_ID` and `GOOGLE_CLIENT_SECRET` or you replace the values directly in the silhouette.conf:

```scala
  google.accessTokenURL="https://accounts.google.com/o/oauth2/token"
  google.redirectURL="http://localhost:9000"
  google.clientID="your.id"
  google.clientSecret="your.secret"
  google.scope="profile email"
```

**Comment by jptissot** [comment]
Well that was it ! 

I was sucessfully able to login on localhost now :) Thanks alot for your help. 

When you said :  "Either you set environment variables with your GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET", do you mean windows environment variables ? I'm sorry if this seems like a dumb question, I'm starting to learn Scala :)

**Comment by akkie** [comment]
Nice, that it works!

Yes, Windows or Linux/Unix environment variables. You can find the documentation for the Play configuration under the following link: https://www.playframework.com/documentation/2.3.x/ProductionConfiguration

The Heroku build files does the same. It sets Linux environment variables as specified in the app.json and then Play replaces this variables in the config.

Let me know if you have further questions.

**Comment by jptissot** [comment]
I have created a pull request with an updated readme.md if that interests you :) Thanks again for your help ! This looks like a great library !

**Comment by nanothermite** [comment]
@akkie, could you kindly list such relevant details that app.json is Heroku specific. I test locally then deploy to my network and simply thought that app.json was read by Silhouette?
